apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adex-webapp-mongo-stateful
  namespace: adex-webapp
  labels:
    app: adex-webapp-mongo-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adex-webapp-mongo-label
  template:
    metadata:
      labels:
        app: adex-webapp-mongo-label
    spec:
      containers:
        - name: adex-webapp-mongo-pod
          image: bidahal/mongodb
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m # this is the minimum cpu that this pod will use
              memory: 1024Mi
            limits: # this is the limit on how much cpu can this pod use
              cpu: 1000m # this 'm' refers to the microns for cpu and 1000 microns = 1 cpu core and 'mi' refers to the megabit for the ram.
              memory: 1Gi
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: adex-webapp-mongo-service
  namespace: adex-webapp
spec:
  selector:
    app: adex-webapp-mongo-label
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017